import { router, json, error, db } from '@appdeploy/sdk';
import { createHash, randomUUID } from 'crypto';
import { notifySubscribers, realtimeSubscriptionRoutes } from './realtime-subscribers';
type Role = 'admin' | 'branch';
type User = { id: string; username: string; name: string; passwordHash: string; role: Role; branchId: string | null; active: boolean; createdAt: number };
type Session = { id: string; tokenHash: string; userId: string; expiresAt: number; createdAt: number };
type Log = { id: string; branchId: string; branchName: string; phone: string; message: string; hasImage: boolean; status: string; detail?: string; at: string; createdAt: number; campaignId: string };
const hash = (v: string) => createHash('sha256').update(v).digest('hex');
async function seed() { const { items } = await db.list<User>('users', { limit: 100 }); if (items.length) return; const p = hash('1234'); await db.add('users', [{ username: 'admin', name: 'Merkez Yönetim', passwordHash: p, role: 'admin', branchId: null, active: true, createdAt: Date.now() }, { username: 'izmit', name: 'İzmit', passwordHash: p, role: 'branch', branchId: 'izmit', active: true, createdAt: Date.now() }, { username: 'korfez', name: 'Körfez', passwordHash: p, role: 'branch', branchId: 'korfez', active: true, createdAt: Date.now() }]); }
async function authToken(token?: string) { if (!token) return null; const { items } = await db.list<Session>('sessions', { filter: { tokenHash: hash(token) } }); const session = items.find(x => x.expiresAt > Date.now()); if (!session) return null; const [user] = await db.get<User>('users', [session.userId]); return user && user.active ? { ...user, id: session.userId } : null; }
async function stateFor(user: User) { const { items: users } = await db.list<User>('users', { limit: 500 }); const { items: logs } = await db.list<Log>('logs', { limit: 1000 }); const visible = user.role === 'admin' ? logs : logs.filter(x => x.branchId === user.branchId); return { user: { id: user.id, username: user.username, name: user.name, role: user.role, branchId: user.branchId }, branches: user.role === 'admin' ? users.filter(x => x.role === 'branch').map(x => ({ id: x.id, username: x.username, name: x.name, branchId: x.branchId, active: x.active })) : [], logs: visible.sort((a,b) => b.createdAt - a.createdAt).slice(0, 1000) }; }
export const handler = router({
  'GET /api/_healthcheck': [async () => { await seed(); return json({ ok: true }); }],
  'POST /api/login': [async ({ body }) => { await seed(); const b = (body || {}) as { username?: string; password?: string }; const { items } = await db.list<User>('users', { filter: { username: String(b.username || '').toLocaleLowerCase('tr-TR') } }); const user = items.find(x => x.passwordHash === hash(String(b.password || ''))); if (!user || !user.active) return error('Kullanıcı adı veya şifre hatalı', 401); const token = randomUUID() + randomUUID(); await db.add('sessions', [{ tokenHash: hash(token), userId: user.id, expiresAt: Date.now() + 2592000000, createdAt: Date.now() }]); return json({ token, ...(await stateFor({ ...user, id: user.id })) }); }],
  'POST /api/state': [async ({ body }) => { await seed(); const b = (body || {}) as { token?: string }; const user = await authToken(b.token); if (!user) return error('Oturum geçersiz', 401); return json(await stateFor(user)); }],
  'POST /api/logout': [async ({ body }) => { const token = String(((body || {}) as { token?: string }).token || ''); const { items } = await db.list<Session>('sessions', { filter: { tokenHash: hash(token) } }); if (items.length) await db.delete('sessions', items.map(x => x.id)); return json({ ok: true }); }],
  'POST /api/branches/create': [async ({ body }) => { const b = (body || {}) as { token?: string; username?: string; name?: string; password?: string }; const admin = await authToken(b.token); if (!admin || admin.role !== 'admin') return error('Yetkisiz', 403); const username = String(b.username || '').trim().toLocaleLowerCase('tr-TR'); if (!username || !b.name || !b.password) return error('Tüm alanlar zorunlu', 400); const { items } = await db.list<User>('users', { filter: { username } }); if (items.length) return error('Kullanıcı adı mevcut', 409); const [id] = await db.add('users', [{ username, name: String(b.name).trim(), passwordHash: hash(String(b.password)), role: 'branch', branchId: username, active: true, createdAt: Date.now() }]); if (!id) return error('Şube oluşturulamadı', 500); await notifySubscribers('state', 'all', { changed: true }); return json({ ok: true, id }); }],
  'POST /api/branches/toggle': [async ({ body }) => { const b = (body || {}) as { token?: string; id?: string }; const admin = await authToken(b.token); if (!admin || admin.role !== 'admin') return error('Yetkisiz', 403); if (!b.id) return error('Şube bulunamadı', 404); const [branch] = await db.get<User>('users', [b.id]); if (!branch || branch.role !== 'branch') return error('Şube bulunamadı', 404); await db.update('users', [{ id: b.id, record: { ...branch, active: !branch.active } }]); await notifySubscribers('state', 'all', { changed: true }); return json({ ok: true }); }],
  'POST /api/logs/create': [async ({ body }) => { const b = (body || {}) as { token?: string; branchId?: string; recipients?: string[]; message?: string; hasImage?: boolean; campaignId?: string }; const user = await authToken(b.token); if (!user) return error('Yetkisiz', 403); let branchId = user.branchId; let branchName = user.name; if (user.role === 'admin') { branchId = String(b.branchId || ''); const { items } = await db.list<User>('users', { filter: { branchId } }); const branch = items.find(x => x.role === 'branch' && x.active); if (!branch) return error('Aktif şube seçimi gerekli', 400); branchName = branch.name; } if (!branchId) return error('Şube hesabı gerekli', 403); if (!Array.isArray(b.recipients) || !b.recipients.length || !String(b.message || '').trim()) return error('Alıcı ve mesaj zorunlu', 400); const now = Date.now(); const records = b.recipients.slice(0,50).map(phone => ({ branchId: branchId!, branchName, phone, message: String(b.message).trim(), hasImage: Boolean(b.hasImage), status: 'Bekliyor', at: new Date(now).toLocaleString('tr-TR'), createdAt: now, campaignId: String(b.campaignId || '') })); const ids = await db.add('logs', records); const created = records.map((x,i) => ({ ...x, id: ids[i] })).filter(x => x.id); await notifySubscribers('state', branchId, { changed: true }); await notifySubscribers('state', 'all', { changed: true }); return json({ records: created }); }],
  'POST /api/logs/result': [async ({ body }) => { const b = (body || {}) as { token?: string; id?: string; status?: string; detail?: string }; const user = await authToken(b.token); if (!user || !b.id) return error('Yetkisiz', 403); const [log] = await db.get<Log>('logs', [b.id]); if (!log || (user.role !== 'admin' && log.branchId !== user.branchId)) return error('Kayıt bulunamadı', 404); await db.update('logs', [{ id: b.id, record: { ...log, status: String(b.status || 'Hatalı'), detail: b.detail, at: new Date().toLocaleString('tr-TR') } }]); await notifySubscribers('state', log.branchId, { changed: true }); await notifySubscribers('state', 'all', { changed: true }); return json({ ok: true }); }],
  ...realtimeSubscriptionRoutes
});
